<?php

namespace AppBundle\Repository;

/**
 * ResaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFullDays()
	{
		$qb = $this->_em->createQuery('
			SELECT r.date
			FROM AppBundle:Resa r			
			GROUP BY r.date
			HAVING r.date >= :now AND COUNT(r) >= 10
			
		')
			->setParameter('now', new \DateTime('now'))
		;
		// HAVING COUNT(r) >= 10
		// à rajouter après tests
					
		return $qb->getResult();
	}
}
