<?php

namespace AppBundle\Repository;

/**
 * ResaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResaRepository extends \Doctrine\ORM\EntityRepository
{
}
