<?php

namespace AppBundle\Repository;

/**
 * ResaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFullDays()
	{
		$today = new \DateTime('now');
		$today->modify('-1 day');
		
		$qb = $this->_em->createQuery('
			SELECT r.date
			FROM AppBundle:Resa r
			JOIN r.persons p
			GROUP BY r.date
			HAVING r.date >= :now
			AND COUNT(p) >= 10			
		')
			->setParameter('now', $today)
		;
		// HAVING COUNT(r) >= 10
		// à rajouter après tests
					
		return $qb->getResult();
	}
}
