# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    calculator:
        class: AppBundle\Services\Calculator
    
    price.twig.filter.extension:        
        class: AppBundle\Services\PriceTwigFilterExtension
        # arguments: ['@translator']
        arguments: ['@calculator']
        public: false
        tags:
            - { name: twig.extension }
    
    date_available:
        class: AppBundle\Form\Validator\Constraints\DateAvailableValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator }
