AppBundle\Entity\Resa:   
    properties:
        date:
            - Date: ~
            - GreaterThanOrEqual: today
            - AppBundle\Form\Validator\Constraints\DateAvailable: ~
        type:
            - Choice:
                choices: [F, H]
        email:
            - NotBlank: ~
            - Email: ~
        # ne fonctionne pas ?
        persons:
            - Count:
                min: 1
                max: 10
                minMessage: 'Aucun visiteur enregistré !'
                maxMessage: 'Vous avez dépassé le nombre maximum de visiteurs par réservation !'