AppBundle\Entity\Resa:
    constraints:
        - AppBundle\Form\Validator\Constraints\TypePossible: ~
    properties:
        date:
            - Date: ~
            - GreaterThanOrEqual: today
            - AppBundle\Form\Validator\Constraints\DateAvailable: ~
        typeResa:
            - Choice:
                choices: [F, H]            
        nom:
            - Length:
                min: 2
                max: 50
                minMessage: 'Le nom est trop court !'
                maxMessage: 'Le nom est trop long !'
        email:            
            - Email: ~     
        persons:
            - Count:
                min: 1
                max: 10
                minMessage: 'Aucun visiteur enregistré !'
                maxMessage: 'Vous avez dépassé le nombre maximum de visiteurs par réservation !'